<a href="https://colab.research.google.com/github/AFy-cyber/Modul-VII-SCPK/blob/main/NeuralNetwork%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import keras
import numpy as np
from sklearn import preprocessing

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [21]:
data=pd.read_csv('drive/My Drive/water_potability.csv')

In [25]:
#parsing data 
X1 = pd.DataFrame(data, columns= ['ph'])
X2 = pd.DataFrame(data, columns= ['Hardness'])
X3 = pd.DataFrame(data, columns= ['Solids'])
X4 = pd.DataFrame(data, columns= ['Chloramines'])
X5 = pd.DataFrame(data, columns= ['Sulfate'])
X6 = pd.DataFrame(data, columns= ['Conductivity'])
X7 = pd.DataFrame(data, columns= ['Organic_carbon'])
X8 = pd.DataFrame(data, columns= ['Trihalomethanes'])
X9 = pd.DataFrame(data, columns= ['Turbidity'])
Y = pd.DataFrame(data, columns= ['Potability'])
X1

ph
0          NaN
1     3.716080
2     8.099124
3     8.316766
4     9.092223
...        ...
3271  4.668102
3272  7.808856
3273  9.419510
3274  5.126763
3275  7.874671

[3276 rows x 1 columns]

In [26]:
#Visual array dummy
datas = np.array([[1,1],[1,0],[0,1],[0,0]])
test = np.array([[1],[0],[0],[0]])
print(datas)
print(test)

[[1 1]
 [1 0]
 [0 1]
 [0 0]]
[[1]
 [0]
 [0]
 [0]]


In [27]:
#Set Data Done
XS = np.array([X1,X2,X3,X4,X5,X6,X7,X8,X9],dtype=int)
XS = XS.transpose()
YS = np.array(Y,dtype=int)
#YS = Y.values.tolist()
XSS = XS[0]
YSS = YS[0]

print(XSS[0])
print(YS)


[-9223372036854775808                  204                20791
                    7                  368                  564
                   10                   86                    2]
[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]


In [28]:

#MODEL dummy
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[9],activation=keras.activations.tanh)])

#Model compile
model.compile(optimizer='adam',loss='mean_squared_error')

In [29]:
#Arsitektur 
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [30]:
#Bobot
weights = model.get_weights()
weights

[array([[ 0.43382752],
        [ 0.16638678],
        [ 0.45705855],
        [ 0.2944789 ],
        [ 0.02070504],
        [ 0.48542452],
        [ 0.03928936],
        [-0.02835381],
        [ 0.6249336 ]], dtype=float32), array([0.], dtype=float32)]

In [31]:
#train dummy
model.fit(XSS,YS,epochs=1000)

Epoch 1/1000
103/103 [==============================] - 13s 1ms/step - loss: 1.1271
Epoch 2/1000
103/103 [==============================] - 0s 930us/step - loss: 1.1019
Epoch 3/1000
103/103 [==============================] - 0s 943us/step - loss: 1.1104
Epoch 4/1000
103/103 [==============================] - 0s 972us/step - loss: 1.1177
Epoch 5/1000
103/103 [==============================] - 0s 882us/step - loss: 1.1212
Epoch 6/1000
103/103 [==============================] - 0s 931us/step - loss: 1.1080
Epoch 7/1000
103/103 [==============================] - 0s 1ms/step - loss: 1.1347
Epoch 8/1000
103/103 [==============================] - 0s 895us/step - loss: 1.1379
Epoch 9/1000
103/103 [==============================] - 0s 927us/step - loss: 1.1099
Epoch 10/1000
103/103 [==============================] - 0s 962us/step - loss: 1.1213
Epoch 11/1000
103/103 [==============================] - 0s 981us/step - loss: 1.1035
Epoch 12/1000
103/103 [==============================] - 0s 899us/

In [32]:
#test data dummy
cek_data = [-9223372036854775808,204,20791,7,368,564,10,86,2]
#cek_data = [1,0]
jawaban = model.predict([cek_data])
jawaban

array([[-1.]], dtype=float32)